---
data:
    dataset: 
        name: TTAVDataset
        root: "/datasets/maestro-v3.0.0"
        sr: &sr 16000
        ac: &ac 1  # audio channels
        n_insts: &n_insts 13
        crop_duration: 2.
        max_tokens: 256
        n_vocab: &n_vocab 10000

model:
    n_insts: *n_insts

    frontend:
        name: LogMel
        sr: *sr
        n_fft: 1024
        hop_length: 160
        n_mels: 128

    encoder:
        name: CRNN
        in_dim: *ac
        dim: 1024
        out_dim: 2496
        n_layers: 3

    decoder:
        name: Transformer
        n_vocab: *n_vocab
        in_dim: 192
        dim: 384
        n_heads: 12
        n_layers: 6
        rope_len: 8192

    frame_head:
        name: MLP
        in_dim: 192
        dim: 256
        out_dim: 128

train:
    num_workers: 16
    precision: null  # null (fp32) | "bf16"
    cfg:
        dropout_prob: 0.1
    optimizer:
        name: AdamW
        lr: 1e-4
        warmup_steps: 1000
    batch_size_per_device: 4
    test_every_n_steps: 10000
    save_every_n_steps: 100000
    training_steps: 2000000
    resume_ckpt_path: "./checkpoints/train/ttav_ave_08b/step=200000_ema.pth"